spring:
  # 데이터베이스 연결 설정
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wjdthddl
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # DB 접속객체 미리만들고 필요할때만 쓰고반납하여 성능개선, 스프링부트2.0이후부터 자동지원
      maximum-pool-size: 10 # 최대 커넥선 개수
      connection-timeout: 30000 # 커넥션 얻기위해 대기하는 최대 시간
      max-lifetime: 1800000 # 커넥션 최대수명

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      # ddl-auto: 애플리케이션 실행 시 스키마(테이블) 처리 전략
      # none: 아무 작업도 하지 않음 (운영 환경 추천)
      # create: 기존 테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      ddl-auto: validate
    properties:
      hibernate:
        # MySQL 8 버전에 맞는 Dialect(방언) 설정
        dialect: org.hibernate.dialect.MySQL8Dialect


  # flyway 설정
  spring:
    flyway:
      enabled: true
      locations: classpath:db/migration # 마이그레이션 SQL 파일이 위치할 경로
      baseline-on-migrate: true # 기존에 테이블이 있는 DB에 Flyway를 처음 적용할 때 사용

# 로깅 레벨 설정
logging:
  level:
    # Hibernate가 실행하는 SQL 쿼리를 DEBUG 레벨로 로그에 출력
    org.hibernate.SQL: DEBUG

# 내장 웹 서버 설정
server:
  port: 8080

# Swagger UI : 운영에서는 URL 노출되어 보안유출 방지를 위해 false처리
springdoc:
  swagger-ui:
    enabled: false